version: '2'
services:
  dstrader:
    build: .
    ports:
#      - "4003:4003"
      - "5901:5900"
    volumes:
      - ./ib/IBController.ini.jdtogni:/home/docker/IBController/IBController.ini
      - ./ib/jts.ini:/home/docker/Jts/jts.ini
      - ./dstrader/${RUNTIME}:/home/docker/dstrader/runtime:rw
    environment:
      - TZ=America/Los_Angeles
      - VNC_PASSWORD=1324
      - TWS_MAJOR_VRSN=10
      - IBC_INI=/home/docker/IBController/IBController.ini
      - IBC_PATH=/opt/IBController
      - TWS_PATH=/home/docker/Jts
      - TWS_CONFIG_PATH=/home/docker/Jts
      - LOG_PATH=/home/docker/Logs
      - JAVA_PATH=/usr/lib/jvm/java-8-openjdk-arm64/jre/
      - TRADING_MODE=${TRADING_MODE} # either paper or live
      - RUNTIME=${RUNTIME}
#      - TWSUSERID= # IB account
#      - TWSPASSWORD= # IB account password
#      - FIXUSERID=
#      - FIXPASSWORD=
      - APP=GATEWAY
#      - SOCAT_LISTEN_PORT=4003
#      - SOCAT_DEST_PORT=4002 # paper = 4002, live 4003
#      - SOCAT_DEST_ADDR=127.0.0.1

